openapi: 3.1.0
info:
  title: PantryPrep API
  version: "1.0"
servers:
  - url: https://pantry-prep-api.kj5irq.workers.dev
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: ok

  /recipes:
    get:
      summary: Search recipes
      parameters:
        - name: search
          in: query
          schema: { type: string }
        - name: tags
          in: query
          schema: { type: string, description: "csv list, e.g. breakfast,freezer" }
        - name: methods
          in: query
          schema: { type: string, description: "freeze,pressure-can" }
      responses:
        "200":
          description: ok
    post:
      summary: Add or update a recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, yield_units, unit_desc, ingredients, steps]
              properties:
                id: { type: string, nullable: true }
                name: { type: string }
                yield_units: { type: integer }
                unit_desc: { type: string }
                methods: { type: string }
                appliances: { type: string }
                tags: { type: string }
                ingredients:
                  type: array
                  items:
                    type: object
                    required: [item, qty, unit]
                    properties:
                      item: { type: string }
                      qty: { type: number }
                      unit: { type: string }
                steps: { type: string }
                storage_options: { type: string }
                reheat_options: { type: string }
                notes: { type: string }
      responses:
        "200":
          description: created

  /planner/plan_batch:
    post:
      summary: Scale ingredients for a target output
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [recipe_id, target_units]
              properties:
                recipe_id: { type: string }
                target_units: { type: integer }
      responses:
        "200":
          description: ok
